steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gihan-danushka-portfolio:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gihan-danushka-portfolio:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gihan-danushka-portfolio'
      - '--image=gcr.io/$PROJECT_ID/gihan-danushka-portfolio:$SHORT_SHA'
      - '--region=asia-south2'
      - '--platform=managed'
      - '--allow-unauthenticated'
